apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: ${{ values.name }}
resources:
  - namespace.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - statefulset.yaml
  - pvc.yaml
  - networkpolicy.yaml
