apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${{ values.name }}-workspace
  namespace: ${{ values.namespace }}
  labels:
    app: paude
    paude.io/session-name: ${{ values.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${{ values.pvcSize }}
  {%- if values.storageClass %}
  storageClassName: ${{ values.storageClass }}
  {%- endif %}
