apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: paude-software-templates
  description: All Paude RHDH Software Templates
spec:
  targets:
    - ./templates/paude-agent/template.yaml
    - ./templates/paude-task/template.yaml
    - ./templates/paude-agent-role/template.yaml
    - ./templates/paude-project/template.yaml
