apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ${{ values.name }}-github-binding
  namespace: ${{ values.argoNS }}
spec:
  params:
    - name: gitRevision
      value: $(body.after)
    - name: gitRepository
      value: $(body.repository.clone_url)
    - name: eventType
      value: $(header.X-GitHub-Event)
    - name: prNumber
      value: $(body.pull_request.number)
    - name: sourceBranch
      value: $(body.pull_request.head.ref)
    - name: targetBranch
      value: $(body.ref)
    - name: prAction
      value: $(body.action)
    - name: checkSuiteConclusion
      value: $(body.check_suite.conclusion)
