apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: paude-project
  owner: ${{ values.owner }}
  lifecycle: experimental
  workBranch: ${{ values.workBranch }}
  repoUrl: https://${{ values.githubServer }}/${{ values.repoOwner }}/${{ values.name }}
