apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: ${{ values.name }}
  backstage.io/kubernetes-id: ${{ values.name }}
  app.kubernetes.io/part-of: ${{ values.name }}
resources:
  - deployment.yaml
  - pvc.yaml
  - configmap-agent.yaml
  {%- if values.agentType == 'openclaw' %}
  - service.yaml
  - route.yaml
  {%- endif %}
