apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${{ values.name }}
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ${{ values.name }}
  port:
    targetPort: web-ui
